color: null
description: null
fieldLayouts:
  c5439bb0-179f-4bfc-8e1b-f9af244df1e9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-11T22:23:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: db0df88a-07e7-4273-8cfe-7a38a1a951d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-11T22:32:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2cd8f16e-a2cc-48fd-909e-fa0695c5cd3a # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2865651-72b8-45a0-8bde-57398db91f44
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ef18963a-ae84-419b-be9d-2341a7c7ee19
        userCondition: null
handle: pages
hasTitleField: true
icon: null
name: Pages
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
