dateModified: 1762900368
email:
  fromEmail: support@itsgippsland.com.au
  fromName: 'Test Site'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    1c9546f7-c050-4cc8-8a0e-5b3e784a9ad9: Pages # Pages
    2cd8f16e-a2cc-48fd-909e-fa0695c5cd3a: Body # Body
    20b0a82a-c851-429c-984c-73cbe652fede: 'Test Site' # Test Site
    67ee7e56-8df3-41da-aea1-50b0581b58c4: Pages # Pages
    79bbcef4-e008-4452-a1e4-9dcd7f8f41a3: 'Public Schema' # Public Schema
    c7b3e94d-1cb3-4cdb-a28d-97d4990eaf17: 'Test Site' # Test Site
system:
  edition: solo
  live: true
  name: 'Test Site'
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
