defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 67ee7e56-8df3-41da-aea1-50b0581b58c4 # Pages
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c7b3e94d-1cb3-4cdb-a28d-97d4990eaf17: # Test Site
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: 'pages/{slug}'
type: channel
